# Generated by Django 5.1.4 on 2024-12-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demoapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("reservation_day", models.CharField(max_length=10)),
                ("seats", models.IntegerField()),
            ],
        ),
    ]
