# Generated by Django 5.1.4 on 2024-12-06 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demoapp", "0002_reservation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="name",
        ),
        migrations.AddField(
            model_name="reservation",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="demoapp.customer",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
