# Generated by Django 5.1.4 on 2024-12-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demoapp", "0003_remove_reservation_name_reservation_customer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="customer",
        ),
        migrations.AddField(
            model_name="customer",
            name="reservation_day",
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name="customer",
            name="seats",
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name="Reservation",
        ),
        migrations.DeleteModel(
            name="Vehicle",
        ),
    ]
