# Generated by Django 5.1.3 on 2024-11-30 03:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="name",
            new_name="Person_name",
        ),
    ]
