# Generated by Django 5.1.4 on 2024-12-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("guest_count", models.IntegerField()),
                ("reservation_time", models.DateField(auto_now=True)),
                ("comments", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=100)),
                ("reservation_day", models.CharField(default=None, max_length=10)),
                ("seats", models.IntegerField(default=1)),
            ],
        ),
    ]
