# Generated by Django 5.1.4 on 2024-12-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_person_reservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="count",
            field=models.IntegerField(default=1),
        ),
    ]
