# Generated by Django 5.1.4 on 2024-12-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_alter_reservation_options_alter_reservation_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={},
        ),
        migrations.AddField(
            model_name="reservation",
            name="booth_table",
            field=models.CharField(
                choices=[("Booth", "Booth"), ("Table", "Table")],
                default="Table",
                max_length=10,
            ),
        ),
    ]
