# Generated by Django 5.1.3 on 2024-11-29 23:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menuapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menu",
            old_name="cousine",
            new_name="cuisine",
        ),
    ]
